server:
  port: 8080

spring:
  application:
    name: world
  profiles:
    active: dev
  main:
    allow-circular-references: true
    # 添加以下mvc配置
  mvc:
      throw-exception-if-no-handler-found: true  # 启用NoHandlerFoundException
  web:
    resources:
      add-mappings: false  # 禁用默认静态资源映射，确保404异常能被抛出
  datasource:
    driver-class-name: ${world.datasource.driver-class-name}
    url: jdbc:mysql://${world.datasource.host}:${world.datasource.port}/${world.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${world.datasource.username}
    password: ${world.datasource.password}
    type: com.alibaba.druid.pool.DruidDataSource
  session:
    # session超时时间，默认一天
    timeout: 86400

  mail:
      host: smtp.qq.com
      port: 587
      username: 2689998090@qq.com
      password: nolbnrzunjssdcjb # QQ邮箱授权码
      default-encoding: UTF-8
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hncs.world.pojo.entity
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值


logging:
  level:
    com:
      example:
        mapper: debug
        service: info
        controller: info


jwt:
  secret: your-jwt-secret-key-change-in-production
  expiration: 30000 # 15分钟

verification:
  code:
    expiration: 60 # 验证码有效期5分钟


