server:
  port: 8080

spring:
  application:
    name: world
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${world.datasource.driver-class-name}
    url: jdbc:mysql://${world.datasource.host}:${world.datasource.port}/${world.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${world.datasource.username}
    password: ${world.datasource.password}
    type: com.alibaba.druid.pool.DruidDataSource
  session:
    # session超时时间，默认一天
    timeout: 86400

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hncs.world.pojo.entity
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值


logging:
  level:
    com:
      example:
        mapper: debug
        service: info
        controller: info

