server:
  port: 8080

spring:
  application:
    name: world-book
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${world.datasource.driver-class-name}
    url: jdbc:mysql://${world.datasource.host}:${world.datasource.port}/${world.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${world.datasource.username}
    password: ${world.datasource.password}
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  #mapper配置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.pojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      example:
        mapper: debug
        service: info
        controller: info

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false  # 禁用原生 Swagger UI

# Knife4j 配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
  # 生产环境建议关闭
  production: false